services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  books:
    build: ./
    ports:
      - 80:3002
    environment:
      - PORT=3002
      - COUNTER_URL=http://counter:3003
  counter:
    image: hansolokhv/counter:0.0.1
    ports:
      - 81:3003
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    depends_on: 
      - storage